apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: agendafacil
spec:
  selector:
    app: agendafacil-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: agendafacil
  labels:
    app: agendafacil-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agendafacil-backend
  template:
    metadata:
      labels:
        app: agendafacil-backend
    spec:
      containers:
        - name: agendafacil-backend
          image: pescador95/agendafacil:quarkus
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "2048Mi"
          env:
            - name: REDIS_BASEURL
              value: "redis://redis-service:6379"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: database-user
                  key: database-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password
                  key: database-password
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: database-url
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: email-user
                  key: email-user
            - name: EMAIL_PWD
              valueFrom:
                secretKeyRef:
                  name: email-password
                  key: email-password                