apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deployment
  namespace: agendafacil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: pescador95/agendafacil:loki
          args:
            - -config.file=/etc/loki/local-config.yaml
          ports:
            - containerPort: 3100
            - containerPort: 9095
---
apiVersion: v1
kind: Service
metadata:
  name: loki-service
  namespace: agendafacil
spec:
  selector:
    app: loki
  ports:
    - name: http-port
      protocol: TCP
      port: 3100
      targetPort: 3100
    - name: grpc-port
      protocol: TCP
      port: 9095
      targetPort: 9095  
