apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: agendafacil
spec:
  selector:
    app: agendafacil-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: agendafacil
  labels:
    app: agendafacil-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agendafacil-redis
  template:
    metadata:
      labels:
        app: agendafacil-redis
    spec:
      containers:
        - name: agendafacil-redis
          image: pescador95/agendafacil:redis
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: "256Mi"
