apiVersion: v1
kind: Service
metadata:
  name: whatsapp-service
  namespace: agendafacil
spec:
  selector:
    app: agendafacil-whatsapp
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-deployment
  namespace: agendafacil
  labels:
    app: agendafacil-whatsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agendafacil-whatsapp
  template:
    metadata:
      labels:
        app: agendafacil-whatsapp
    spec:
      containers:
        - name: agendafacil-whatsapp
          image: pescador95/agendafacil:whatsapp
          ports:
            - containerPort: 4000
          resources:
            limits:
              memory: "512Mi"
          env:
            - name: WHATSAPP_PORT
              value: "4000"
            - name: QUARKUS_BASEURL
              value: "http://backend-service:3000"
