apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: agendafacil
spec:
  selector:
    app: agendafacil-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
