apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: agendafacil
spec:
  selector:
    app: agendafacil-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
