apiVersion: v1
kind: Service
metadata:
  name: loki-service
  namespace: agendafacil
spec:
  selector:
    app: loki
  ports:
    - name: http-port
      protocol: TCP
      port: 3100
      targetPort: 3100
    - name: grpc-port
      protocol: TCP
      port: 9095
      targetPort: 9095  
