apiVersion: v1
kind: Service
metadata:
  name: collector-service
  namespace: agendafacil
spec:
  selector:
    app: otel-collector
  ports:
    - name: grpc-port
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: http-port
      protocol: TCP
      port: 4318
      targetPort: 4318
    - name: metrics-port
      protocol: TCP
      port: 8888
      targetPort: 8888    