apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: agendafacil
spec:
  selector:
    app: agendafacil-prometheus
  ports:
    - name: grpc-port
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: http-port
      protocol: TCP
      port: 9091
      targetPort: 9091   