apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: agendafacil
spec:
  selector:
    app: agendafacil-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
