apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: agendafacil
  labels:
    app: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agendafacil-redis
  template:
    metadata:
      labels:
        app: agendafacil-redis
    spec:
      containers:
        - name: agendafacil-redis
          image: pescador95/agendafacil:redis
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: "256Mi"
