apiVersion: v1
kind: Service
metadata:
  name: telegram-service
  namespace: agendafacil
spec:
  selector:
    app: agendafacil-telegram
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
