apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-deployment
  namespace: agendafacil
  labels:
    app: agendafacil-telegram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agendafacil-telegram
  template:
    metadata:
      labels:
        app: agendafacil-telegram
    spec:
      containers:
        - name: agendafacil-telegram
          image: pescador95/agendafacil:telegram
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "512Mi"
          env:
            - name: QUARKUS_BASEURL
              value: "http://backend-service:3000"
            - name: TELEGRAM_PORT
              value: "5000"
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-token
                  key: telegram-token
            - name: TELEGRAM_RELEASE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-release-token
                  key: telegram-release-token