apiVersion: v1
kind: Service
metadata:
  name: tempo-service
  namespace: agendafacil
spec:
  selector:
    app: tempo
  ports:
    - name: http-port
      protocol: TCP
      port: 3200
      targetPort: 3200
    - name: grpc-port-4417
      protocol: TCP
      port: 4417
      targetPort: 4417
    - name: grpc-http-port-4418
      protocol: TCP
      port: 4418
      targetPort: 4418
    - name: grpc-port
      protocol: TCP
      port: 9096
      targetPort: 9096      
