apiVersion: v1
kind: Service
metadata:
  name: whatsapp-service
  namespace: agendafacil
spec:
  selector:
    app: agendafacil-whatsapp
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
