apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agendafacil-ingress
  namespace: agendafacil
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type,Authorization,X-Tenant"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS, PUT, DELETE"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "*.localhost"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
                  
    - host: "*.agendafacil.app"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
                  
    - host: backend.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 3000       
                             
    - host: telegram.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: telegram-service
                port:
                  number: 5000
    - host: whatsapp.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whatsapp-service
                port:
                  number: 4000
                  
    - host: grafana.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-service
                port:
                  number: 9191       
                                
    - host: grafana.agendafacil.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-service
                port:
                  number: 9191
                    
    - host: prometheus.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-service
                port:
                  number: 9090       
                                
    - host: prometheus.agendafacil.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-service
                port:
                  number: 9090                                  