kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: agendafacil-cluster
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 9191
        hostPort: 9191
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 9090
        hostPort: 9090
        listenAddress: "0.0.0.0"
        protocol: TCP                 
  - role: worker
  - role: worker
