services:
  whatsapp:
    container_name: whatsapp-service
    image: pescador95/agendafacil:whatsapp
    mem_limit: 512m
    build:
      context: ../
      dockerfile: Dockerfile.whatsapp
    env_file:
      - ../../.env
    ports:
      - "4000:4000"
