FROM node:latest AS builder

WORKDIR /build

COPY /whatsapp/package.json ./

RUN npm install --silent

COPY /core ./core

COPY /whatsapp ./whatsapp

FROM node:latest

WORKDIR /app

COPY --from=builder /build .

ENV PORT=4000

EXPOSE $PORT

CMD ["node", "./whatsapp/index.js"]