FROM node:latest AS builder

WORKDIR /build

COPY /telegram/package.json ./

RUN npm install --silent

COPY /core ./core

COPY /telegram ./telegram

FROM node:alpine

WORKDIR /app

COPY --from=builder /build .

ENV PORT=5000

EXPOSE $PORT

CMD ["node", "./telegram/index.js"]