

services:
  db:
    container_name: db-service
    image: pescador95/agendafacil:db
    mem_limit: 256m
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ../.env
    ports:
      - "5433:5432"
